project:
  type: website

website:
  title: "xingyuanzhao.github.io"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: 2023 Summer Project
        menu:
          - href: summer2023.qmd
            text: 2023 Summer Project Overview
          - href: question.qmd
            text: Research Question
          - href: litreview.qmd
            text: Literature Review
          - href: variable.qmd
            text: Variable
          - href: hypothesis.qmd
            text: Hypothesis
          - href: method.qmd
            text: Model of Interest
          - href: data.qmd
            text: Data
          - href: finding.qmd
            text: Findings
          - href: reference.qmd
            text: References

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

