project:
  type: website

website:
  title: "xing-yuan-zhao.github.io"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: 7V81 Summer Project
        menu:
          - href: proposal.qmd
            text: Proposal
          - href: presentation1.qmd
            text: Proposal Presentation
          - href: final.qmd
            text: Final Project
          - href: presentation2.qmd
            text: Final Presentation
          - href: reference.qmd
            text: References
      - text: 6319 Book Project
        menu:
          - href: book_presentation.qmd
            text: Book Presentation
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

