---
title: "Research Proposal Presentation"
format: revealjs
---

### Topic of Interest and motivations

#### Conventional wisdom:

-   Conservatives should be more hawkish than liberals.

#### Abnormality:

-   US conservatives are less enthusiastic about supporting Ukraine fighting against Russia

-   [19 GOP lawmakers urged Biden to stop sending "unrestrained" aid and weapons to Ukraine ( Olafimihan Oshin, 2023)](https://thehill.com/homenews/house/3961754-gop-lawmakers-urge-biden-to-stop-sending-unrestrained-aid-weapons-to-ukraine/)

-   [Donald Trump has also claimed to try to broker peace in Ukraine ( Cheryl Teh, 2022; Tom Porter, 2023)](https://www.businessinsider.com/trump-offers-lead-group-to-mediate-peace-russia-2022-9)

------------------------------------------------------------------------

#### Abnormality Cont'd:

-   European conservatives are more involved than American conservatives:

    -   [Boris Johnson, the former Prime Minister and the leader of the Conservative Party, tried to convince Trump to support Ukraine](https://www.theguardian.com/politics/2023/may/26/boris-johnson-meeting-donald-trump-ukraine-us-tour)

    -   [Italian right wing leader, Meloni, is willing to risk unpopularity to support Ukraine (Amante, 2023)](https://www.reuters.com/world/europe/italys-meloni-ready-risk-unpopularity-over-support-ukraine-2023-03-21/)

    -   [Poland, led by United Right, also has been supported Ukraine almost since day one and pleged a lot by its GDP size](https://www.economist.com/graphic-detail/2022/05/02/which-countries-have-pledged-the-most-support-to-ukraine)

------------------------------------------------------------------------

### Research Question

So now we can see a very counter-intuitive problem: **What is discouraging American conservatives from taking a more hawkish stance in support of Ukraine?**

------------------------------------------------------------------------

### Hypothesis

H1: Conservatives in the US are built differently. They hold different sets of beliefs than other conservatives, such as isolationism.(Clarke and Ricketts, 2017; Rolf, 2021; Cha, 2016; Clark et al., 2016)

H2: They genuinely believe that supporting Ukraine will lead to WW3 or nuclear war, and they want to avoid that.

H3: Their arguments are based on economics. Their perception of inflation leads to their war-weariness.

------------------------------------------------------------------------

### Hypothesis Cont'd

H4: It is caused by polarization. They are only against what Biden supports. (Iyengar et al., 2019; Pierson and Schickler, 2020)

H5: They are misled by Russian bots.(Stukal wt al., 2019; Gorwa and Guilbeault, 2020; Hagen et al., 2022)

I must clarify that the research does not aim to test whether their arguments are true or not, but how these beliefs interact with conservative individuals' attitudes toward supporting Ukraine.

------------------------------------------------------------------------

### Variables Draft

DV: Whether a comment supports Ukraine

IV: The predicting factors in the said hypotheses

------------------------------------------------------------------------

### Data of Interest

H1-H4: Youtube comments[(tuber)](https://github.com/soodoku/tuber)

H5: Twitter[(kaggle)](https://www.kaggle.com/datasets/bwandowando/ukraine-russian-crisis-twitter-dataset-1-2-m-rows)

------------------------------------------------------------------------

### Method of Interest

Text as Data

H1-H4: Sentiment Analysis

H5: Social Network

- First, I will use the Tuber package to extract Youtube comments from conservative media.

- Then I will process these comments and tokenize them to create a document by term matirx.

---

### Method Cont'd

- After that, I will try some word frequency analysis or clustering to find out any features I may have ignored. If there are any, I will iterate my hypotheses.

- Finally, I will do sentiment analysis for the first four hypotheses, and maybe social network analysis for hypothesis five, because I need retweets to show the relationship between the Russian bots and the retweeters.

------------------------------------------------------------------------

### Bibliography

Cha, Taesuh. "The return of Jacksonianism: The international implications of the Trump phenomenon." The Washington Quarterly 39.4 (2016): 83-97.

Clark, D. H., Fordham, B. O., & Nordstrom, T. (2016). Political party and presidential decisions to use force: Explaining a puzzling nonfinding. Presidential Studies Quarterly, 46(4), 791-807.

Clarke, Michael, and Anthony Ricketts. "Donald Trump and American foreign policy: The return of the Jacksonian tradition." Comparative Strategy 36.4 (2017): 366-379.

---

### Bibliography

George, Justin, and Todd Sandler. "NATO defense demand, free riding, and the Russo-Ukrainian war in 2022." Journal of industrial and business economics (2022): 1-24.

Gorwa, Robert, and Douglas Guilbeault. "Unpacking the social media bot: A typology to guide research and policy." Policy & Internet 12.2 (2020): 225-248.

Hagen, Loni, et al. "Rise of the machines? Examining the influence of social bots on a political discussion network." Social Science Computer Review 40.2 (2022): 264-287.

---

### Bibliography

Iyengar, Shanto, et al. "The origins and consequences of affective polarization in the United States." Annual review of political science 22 (2019): 129-146.

Pierson, Paul, and Eric Schickler. "Madison's constitution under stress: A developmental analysis of political polarization." Annual Review of Political Science 23 (2020).

Rolf, Jan Niklas. "Donald Trump's Jacksonian and Jeffersonian foreign policy." Policy Studies 42.5-6 (2021): 662-681.

---

### Bibliography

Sides, John, Michael Tesler, and Lynn Vavreck. "Hunting where the ducks are: Activating support for Donald Trump in the 2016 Republican primary." Journal of Elections, Public Opinion and Parties 28.2 (2018): 135-156.

Stukal, Denis, et al. "For whom the bot tolls: A neural networks approach to measuring political orientation of Twitter bots in Russia." Sage Open 9.2 (2019): 2158244019827715.

Uscinski, Joseph E., et al. "American politics in two dimensions: partisan and ideological identities versus anti‐establishment orientations." American Journal of Political Science 65.4 (2021): 877-895.

---

### The End

[Home](index.html)
