---
title: "References"
---

Cha, Taesuh. "The return of Jacksonianism: The international implications of the Trump phenomenon." The Washington Quarterly 39.4 (2016): 83-97.

Clark, D. H., Fordham, B. O., & Nordstrom, T. (2016). Political party and presidential decisions to use force: Explaining a puzzling nonfinding. Presidential Studies Quarterly, 46(4), 791-807.

Clarke, Michael, and Anthony Ricketts. "Donald Trump and American foreign policy: The return of the Jacksonian tradition." Comparative Strategy 36.4 (2017): 366-379.

George, Justin, and Todd Sandler. "NATO defense demand, free riding, and the Russo-Ukrainian war in 2022." Journal of industrial and business economics (2022): 1-24.

Gorwa, Robert, and Douglas Guilbeault. "Unpacking the social media bot: A typology to guide research and policy." Policy & Internet 12.2 (2020): 225-248.

Hagen, Loni, et al. "Rise of the machines? Examining the influence of social bots on a political discussion network." Social Science Computer Review 40.2 (2022): 264-287.

Iyengar, Shanto, et al. "The origins and consequences of affective polarization in the United States." Annual review of political science 22 (2019): 129-146.

Pierson, Paul, and Eric Schickler. "Madison's constitution under stress: A developmental analysis of political polarization." Annual Review of Political Science 23 (2020).

Rolf, Jan Niklas. "Donald Trump's Jacksonian and Jeffersonian foreign policy." Policy Studies 42.5-6 (2021): 662-681.

Sides, John, Michael Tesler, and Lynn Vavreck. "Hunting where the ducks are: Activating support for Donald Trump in the 2016 Republican primary." Journal of Elections, Public Opinion and Parties 28.2 (2018): 135-156.

Stukal, Denis, et al. "For whom the bot tolls: A neural networks approach to measuring political orientation of Twitter bots in Russia." Sage Open 9.2 (2019): 2158244019827715.

Uscinski, Joseph E., et al. "American politics in two dimensions: partisan and ideological identities versus anti‐establishment orientations." American Journal of Political Science 65.4 (2021): 877-895.
